apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: mylabs
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: lab  
