apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinitlab
  namespace: lab
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:     
      containers:
      - name: nginx
        image: nginx
      - name: busybox
        image: busybox
        command:
         - sleep
         - "500"
      initContainers:
      - name: busyboxy
        image: busybox
        command: ['sh', '-c', 'echo $USER $PASSWORD']
        envFrom:
        - configMapRef:
            name: lab 
        - secretRef:
            name: lab           
