apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: web
spec:
  containers:
    - name: nginx
      image: nginx
  initContainers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "10"
