apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  namespace: mzlabs
  labels:
    app: nginx
    role: webserver
spec:
  type: ClusterIP
  selector:
    app: nginx
    role: webserver
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
