apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab10
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - scheduling-m04
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
            name: lab10
