apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinitlab
  namespace: lab
  labels:
    app: nginx
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      app: busybox
  template:
    metadata:
      labels:
        app: nginx
        app: busybox
    spec:
      initContainers:
      - name: busyboxinit
        image: busybox
        envFrom:
        - configMapRef:
            name: lab
        - secretRef:
            name: lab
        command: ['sh', '-c', 'echo $USER $PASSWORD']
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: busybox
        image: busybox
        ports:
        - containerPort: 80
        command:
        - sleep
        - "500"
