apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
      annotations:
          AppVersion: "3.4"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
