apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: lab
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node
                operator: In
                values:
                - lab
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: team
        operator: "Equal"
        value: devops
        effect: "NoSchedule"  
