apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mzlabs
  name: nginx-deployment
  labels:
    app: nginx
    role: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      role: webserver
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: webserver
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
