apiVersion: v1
kind: Service
metadata:
  name: myservise14
  namespace: lab14
spec:
  type: NodePort
  selector:
    role: lab14
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      