apiVersion: v1
kind: Pod
metadata:
  name: web14
  namespace: lab14
  labels:
    role: lab14
spec:
  containers:
  - name: nginx
    image: nginx
  - name: bitnami-fluent-bit
    image: bitnami/fluent-bit
  initContainers:
  - name: busybox
    image: busybox
    command:
    - ls 
    - /etc
